identifier: lbo825q8h791a4h9
appPort: 1864
staticPort: 1668
reloadPort: 2667
hostName: localhost
projectName: my-blog
homeFolder: /home/aes/Projects/Angular/projects-book/my-blog
distFolder: dist/my-blog
outDir: /home/aes/Projects/Angular/projects-book/my-blog/dist/static
handle404: ''
allowErrorCollect: false
